# Generated by Django 3.0.5 on 2021-06-01 08:35

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answers', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('level_of_different', models.FloatField(default=2.5)),
                ('link_media', models.FileField(blank=True, null=True, upload_to='exam/')),
                ('same_questions', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=2)),
                ('id_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.Exams')),
            ],
        ),
    ]
