# Generated by Django 3.0.5 on 2021-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_questions_correct_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_question',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
